### PR TITLE
Switch jekyll theme

### PR DESCRIPTION
**Pull request by ptmerz**
Updated the website to use the minimal mistakes theme as discussed in #34.

Main changes include
* A landing page using a similar style as http://www.livecomsjournal.org/
* A main menu on top of the page linking to the single pages
* A sidebar navigation containing links to the subtitles of the respective document (makes long pages easier to navigate)

Downsides of the approach / possible improvements:
* All navigation elements are static - if pages are changed, the file _data/navigation.yml needs to be regenerated. There are ways to get an automatic toc of the page (see e.g. https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/, on the right side), but I did not find a way to put it in the sidebar (and hence have it always visible). As I didn't want to create all navigation elements by hand, I used a little python script, which I am adding to this pull request. It's not excessively smart, but it's doing its job.
* The readability of the sidebar strongly depends on the length of the subheadings of the page. Possible solutions:
    1. Use short titles.
    2. Make the script smarter, allowing to have short versions of the headings in the sidebar.
    3. Manually edit the navigation.

### CODE REVIEW

**Comment by ptmerz** [comment]
OK, it seems I created a merge conflict. I'll update the pull request!

**Comment by davidlmobley** [comment]
Thanks, @ptmerz !! I'm not a pro with github pages -- is there a way to preview the changes before merging?

**Comment by ptmerz** [comment]
OK, merge conflicts should be resolved.

@davidlmobley Good question, I'm looking into that now. I have a jekyll environment on my computer, so I can certainly have @mrshirts have a look at it - I'll check if there is a way to have a preview on github pages for everyone else to see.

**Comment by ptmerz** [comment]
We had a round of review with @mrshirts this afternoon (small changes visually, but difficult to get jekyll to do what we wanted).

I did not find an easy way to preview the changes of a PR. I am attaching two screen shots to give you an impression. Given the current development stage, I would suggest that if you don't have major objections, we can go ahead and merge the PR and go on improving from there.

Landing Page:
Landing Page

Policies page with sidebar navigation:
Policies page with sidebar navigation

**Comment by davidlmobley** [comment]
This looks good, much more official!

**Pull request merged**
