### PR TITLE
Siderius review

### PR DESCRIPTION
**Pull request by dwsideriusNIST**

### CODE REVIEW

**Comment by dwsideriusNIST** [comment]
For some reason, this wants to merge 68 commits into the bylaws branch. That is NOT what I intended.

**Comment by mrshirts** [comment]
Hmm.  Maybe try doing a diff on your local branch to isolate the changes
you want, creating a new branch, resetting that new branch to the head of
origin/bylaws, and the reimplementing the changes.

https://stackoverflow.com/questions/1628088/reset-local-repository-branch-to-be-just-like-remote-repository-head

On Fri, Dec 1, 2017 at 7:48 AM, Daniel W. Siderius <notifications@github.com

**Comment by davidlmobley** [comment]
I think what's going on here is that you've updated to `master` (or based your branch off of `master`) and Michael's `bylaws` branch has not. So your PR (if you reopen it) would (a) update his branch to `master` AND incorporate your changes to `bylaws`. So this might be a good thing, otherwise @mrshirts will have to do it later before merging his. :)

**Comment by dwsideriusNIST** [comment]
It was some variant of that. I reverted to a clean copy of bylaws, then redid my changes in PR #129

**Pull request closed without merging**
