### PR TITLE
updated for providing information.

### PR DESCRIPTION
**Pull request by mrshirts**
Making it clear that we need author affiliations (including departments) and ORCID id for the metadata upon acceptance (David, I need those to post your article as well), for entering the article metadata on Scholastica. 

I wonder if we should explicitly put a place for ORCID id in to the template. and to make sure the templates include affiliation department; that would reduce problems after acceptance getting all the information.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Oh, I see, you need *all authors*; this is clear in your instructions but not in your comment. I'll work on getting them for mine.

**Comment by dwsideriusNIST** [comment]
@davidlmobley, I'm definitely in favor of including an author identifier somewhere in the paper. Also agree that the front matter is already large, so I would prefer an "AUTHOR INFORMATION" section at the end of the document.

Just to be devil's advocate: Let's make sure that our procedure is reliant on ORCID; it seems to be winning the competition of author identification, but that competition is ongoing.

**Comment by dwsideriusNIST** [comment]
Take a look at page 22 of https://github.com/dmzuckerman/Sampling-Uncertainty/blob/orcid/main.pdf; here is an example of how the ORCIDs could be implemented in a paper.

**Comment by dmzuckerman** [comment]
Once again, as we find ourselves taking on more clerical work as editors, I suggest to request Scholastica to implement an automated process.  ORCIDs are indeed fairly common.

**Comment by davidlmobley** [comment]
Also it's unclear to me that right now there is actually a way to put ORCIDs for all authors into the Scholastica metadata, even though @mrshirts just updated the documentation to indicate we should do this.

**Comment by dwsideriusNIST** [comment]
> Take a look at page 22 of https://github.com/dmzuckerman/Sampling-Uncertainty/blob/orcid/main.pdf; here is an example of how the ORCIDs could be implemented in a paper.

If we go this route, I would suggest adding a macro function to create the ORCID links from author information (like the \affil[X] variable) to avoid typos / HREF mistakes.

**Comment by davidlmobley** [comment]
Just to be clear, there are two distinct issues relating to ORCIDs:
1) Do we put this info for all authors into the metadata? We should, but it goes through Scholastica's website and the editor or authors has to type (or copy and paste) it in; if after acceptance it has to be the editor.
2) Do we put this info in the article itself? Probably a good idea -- if we have the authors do it up front then they will have it on hand and it increases the likelihood they will put it into Scholastica. Otherwise we're asking them to get in touch with all their co-authors and get their ORCIDs as a final step towards publication, which will delay things (e.g. I'm having to wait about a week for the last of my co-author ORCIDs) to trickle in

So I propose we update author guidelines and templates to put in info they should put ORCIDs in papers (with an appropriate spot in the PDF).

**Comment by mrshirts** [comment]
> Do we put this info for all authors into the metadata? We should, but it goes through Scholastica's website and the editor or authors has to type (or copy and paste) it in; if after acceptance it has to be the editor.

The default is that it should be entered by the authors themselves, upon submitting a paper. This can be enforced by just having the editors check that the information we want is there on the first review, so that when resubmitted, it is there.  We should think about whether we want to require everything from everyone, but otherwise - that's where the check goes.

>Do we put this info in the article itself? 

This isn't controlled at all by Scholastica, so there, we have to enforce by author instruction.  Probably we do want the same information in both places.

**Comment by dmzuckerman** [comment]
> This can be enforced by just having the editors check that the information we want is there on the first review
We should add to editor checklist, if possible on Scholastica so they can't avoid seeing it.

**Comment by dwsideriusNIST** [comment]
> Just to be clear, there are two distinct issues relating to ORCIDs:
> 
> 1. Do we put this info for all authors into the metadata? We should, but it goes through Scholastica's website and the editor or authors has to type (or copy and paste) it in; if after acceptance it has to be the editor.

Presumably, this is for the managing editors to handle, right?

> 2. Do we put this info in the article itself? Probably a good idea -- if we have the authors do it up front then they will have it on hand and it increases the likelihood they will put it into Scholastica. Otherwise we're asking them to get in touch with all their co-authors and get their ORCIDs as a final step towards publication, which will delay things (e.g. I'm having to wait about a week for the last of my co-author ORCIDs) to trickle in
> 
> So I propose we update author guidelines and templates to put in info they should put ORCIDs in papers (with an appropriate spot in the PDF).

How is the rough example shown in https://github.com/dmzuckerman/Sampling-Uncertainty/blob/orcid/main.pdf? It is a shameless reproduction of the author ID section in ACS journals.

**Question: ** Are we _requiring_ ORCID to be the author identifier? Or should the author ID block be a bit more agnostic and allow ResearcherID, ScopusID, etc.? I'm thinking that the macro that creates that block could be written to handle any of those systems' APIs.

**Comment by mrshirts** [comment]
> Presumably, this is for the managing editors to handle, right?

yes, we can explicitly say that in the instructions

> **Question: ** Are we requiring ORCID to be the author identifier? Or should the author ID block be a bit more agnostic and allow ResearcherID, ScopusID, etc.? I'm thinking that the macro that creates that block could be written to handle any of those systems' APIs.

Good question.  Right now, ORCID explicitly is a field in the Scholastica metadata, so it makes sense to use that one.

**Comment by dwsideriusNIST** [comment]
I made a slight revision to the CLS file to create the ORCID block. Results are visible here: https://github.com/dmzuckerman/Sampling-Uncertainty/blob/orcid/main.pdf, page 22

The ORCIDs are input via a macro function, e.g.:

\orcid{Daniel W. Siderius}{https://orcid.org/}{0000-0002-6260-7727}
\orcid{Daniel M. Zuckerman}{https://orcid.org/}{0000-0001-7662-2031}

Ideally, I would like argument 1 to reference the author name from the \author function, but I haven't been able figure out how to access that variable in the main CLS file. Help?

**Comment by davidlmobley** [comment]
@liantze is this (referencing author name in the class file) something you have expertise in?

**Comment by liantze** [comment]
Sorry I just saw this! Usually `\@author` should do it but I'm not quite sure yet of the use case here. Do you mean you need to fish out each individual author name? This could be tricky as it may require fiddling with authblk.

Alternatively we could extend `\author` so that it takes another mandatory argument i.e. the ORCID?

```
\author[1*]{Firstname Middlename Surname}{MANDATORY ORCID HERE}
```

**Comment by dwsideriusNIST** [comment]
@liantze, thank you for the advice. I do not think that extending \author is the right approach, as it locks in the ORCID author identification; using separate macros allows us to switch to a different identifier in the future, if needed.

A minimally working example is at https://github.com/dmzuckerman/Sampling-Uncertainty/tree/ASAP_test

In main.tex, I invoke the author identifier via lines like:

\orcid{Daniel W. Siderius}{0000-0002-6260-7727}
\orcid{Daniel M. Zuckerman}{0000-0001-7662-2031}

What I would like to do is something like:

\orcid{\author[5]}{0000-0002-6260-7727}
\orcid{\author[6]}{0000-0001-7662-2031}

or similar, maybe:

\orcid[6]{0000-0002-6260-7727}
\orcid[7]{0000-0001-7662-2031}

And then automatically create the text box (see the PDF in that repo for the formatted version):

Author Information
ORCID:
Daniel W. Siderius: 0000-0002-6260-7727
Daniel M. Zuckerman: 0000-0001-7662-2031

I've tried entering \@author[6] in the first argument of \orcid, but it just renders as "author" rather than inserting the name of author 6.

**Comment by liantze** [comment]
That can indeed by tricky... The numbers aren't associated with each name by `authblk`. So you can have `\author[1,3]{An Author}` because they're affiliated to both institutions 1 and 3. `1,3` (and even `$\diamond$` etc if that's what's placed in the square brackets) are just printed as superscripts after `An Author`, not stored.

`\orcid[3]` may then be confusing—is that the 3rd author or the 3rd institution?

**Comment by dwsideriusNIST** [comment]
Aha... I didn't know that the bracketed numbers actually referred to affiliations.

My intention was for `\orcid[3]` to refer to the third author; based on your answer, it seem like we cannot refer back to an author name as if it were a stored variable.

So, I would propose (for the time being) that we just use the less elegant, but simple macros:

\orcid{Daniel W. Siderius}{0000-0002-6260-7727}
\orcid{Daniel M. Zuckerman}{0000-0001-7662-2031}

We could make this more complicated in the future, if it proves necessary, but I think this is a straightforward solution to the need.

**Pull request merged**
